Update info.html
AMC-Robotics/AMC-Robotics.github.io pull request #16
Opened 2020-11-13 03:32 UTC by VinLi04

2020-11-14 01:06 UTC, Yassin-Kortam2 commented on info.html
> -    <link href="style.css" rel="stylesheet">
This is needed for the css

2020-11-14 01:06 UTC, Yassin-Kortam2 commented on info.html
> +    <body class="info">
its better as an ID than a class because this is only one page

2020-11-14 01:27 UTC, Yassin-Kortam2 commented on info.html
>  window.onscroll = function() {myFunction()};
script tag should be inside the body tag

2020-11-14 01:29 UTC, Yassin-Kortam2 requested changes
The instructions should be on a pdf document that is linked to on the info page, not directly on it. Also, please clean up the layout. Paragraphs have no padding, the font is still the default, links need to be stylized better.

2020-11-18 00:00 UTC, ramaduraianirudh9867 commented on info.html
> +    <body class="info">
@kellylin118 @VinLi04 @aparna2003

2020-11-18 00:00 UTC, ramaduraianirudh9867 commented on info.html
>  window.onscroll = function() {myFunction()};
@kellylin118 @VinLi04 @aparna2003

2020-11-18 00:01 UTC, ramaduraianirudh9867 commented
@kellylin118 @VinLi04 @aparna2003 please see the comments above, and fix as appropriate.

2020-11-20 00:56 UTC, closed without merging